// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt_waZ1Q0aZx-KNMwcWg15iLFET1VOM4k',
    appId: '1:932078272793:web:1c0423a1e97a7e94d60588',
    messagingSenderId: '932078272793',
    projectId: 'zadinga-fl',
    authDomain: 'zadinga-fl.firebaseapp.com',
    storageBucket: 'zadinga-fl.appspot.com',
    measurementId: 'G-WN3LPQM9ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhawyvY-e60qP3GRW4tvupLB5qXTMjbF8',
    appId: '1:932078272793:android:c135a83aa3df4636d60588',
    messagingSenderId: '932078272793',
    projectId: 'zadinga-fl',
    storageBucket: 'zadinga-fl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqTPVSJXS19JjI3jFzvNbpt9pI7qhCfwE',
    appId: '1:932078272793:ios:2de5471c81ba4709d60588',
    messagingSenderId: '932078272793',
    projectId: 'zadinga-fl',
    storageBucket: 'zadinga-fl.appspot.com',
    iosClientId: '932078272793-api6trv2j7jhnkqsmffedl0fqlfolcqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqTPVSJXS19JjI3jFzvNbpt9pI7qhCfwE',
    appId: '1:932078272793:ios:2de5471c81ba4709d60588',
    messagingSenderId: '932078272793',
    projectId: 'zadinga-fl',
    storageBucket: 'zadinga-fl.appspot.com',
    iosClientId: '932078272793-api6trv2j7jhnkqsmffedl0fqlfolcqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSample',
  );
}
